### ISSUE TITLE
Jsonlines format conversion 

### ISSUE THREAD

**Issue by ghost** [juntaoy/dali-bridging#1]
Hi, @juntaoy 

Thanks for your brilliant work!

I notice that different bridging corpora are from different original formats. And scicorp corpus is even annotated on the span level. Since different tokenizer might potentially contribute to model performance, is it possible you can share the pre-processing with the format conversion?   

Thanks.

**Comment by juntaoy** [comment]
Hi @Byron309 
The scicorp corpus comes with conll format as well, so I get the tokenization form there and then write a script to align the bridging annotations with the tokens from the conll format. It is a bit painful:) and involving few other scripts I get from somewhere else. The easiest way is just to send you the JSON files instead. Please drop me an email if you want the JSON files. Due to some copyrights issue, I might need to confirm with you that you have the original files for ARRAU or OntoNotes in case you also need the files for other corpora.

**Comment by ghost** [comment]
Thanks for your prompt reply! I have sent you an email.
